namespace FoodDrinkApp.Services;

/// <summary>
/// Stores the optional MockAPI endpoint used by the catalogue service.
/// </summary>
public static class MockApiConfig
{
    // Replace this with the Resource endpoint generated by mockapi.io.
    // Example: https://682xxxx.mockapi.io/api/v1/foods
    /// <summary>
    /// Gets the configured MockAPI resource endpoint, or an empty string for local fallback mode.
    /// </summary>
    public const string EndpointUrl = "";

    /// <summary>
    /// Gets whether a remote endpoint is available for catalogue operations.
    /// </summary>
    public static bool IsConfigured => !string.IsNullOrWhiteSpace(EndpointUrl);
}
